Add option to install the self-contained binary version of pnpm
pnpm/action-setup pull request #78
Opened 2023-03-31 04:59 UTC by tksst

Related to #31
close #18

Introduce new input `nodejs_bundled`. If true, install [@pnpm/exe](https://www.npmjs.com/package/@pnpm/exe)

This new option is convenient for Node.js14+npnpm8 or similar.

2023-07-25 11:34 UTC, KSXGitHub requested changes

2023-07-25 11:34 UTC, KSXGitHub commented on README.md
> +
Instead of requiring user to specify this option, we should automatically install `@pnpm/exe` if the version is greater than `6.17.1`.

2023-07-25 11:34 UTC, KSXGitHub commented on src/install-pnpm/run.ts
> +
```suggestion
```

2023-07-26 06:36 UTC, KSXGitHub commented on README.md
> +
OK. There is complexity involved, so I guess this option is valid.

2023-07-26 06:57 UTC, KSXGitHub commented
I have merged your commits into a new PR: https://github.com/pnpm/action-setup/pull/92

2023-07-26 07:19 UTC, tksst commented
switch to #92 and close this PR

2023-07-26 07:19 UTC, closed without merging